#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := project

EXTRA_COMPONENT_DIRS += $(PROJECT_PATH)/components/speech_recognition \
    					$(PROJECT_PATH)/components/button

include $(IDF_PATH)/make/project.mk
