#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := project

EXTRA_COMPONENT_DIRS += $(PROJECT_PATH)/components/speech_recognition \
    					$(PROJECT_PATH)/components/button \
						$(PROJECT_PATH)/components/esp_cmd \
						$(PROJECT_PATH)/components/i2c_master \
						$(PROJECT_PATH)/components/aht20

include $(IDF_PATH)/make/project.mk
